### ISSUE TITLE
Deploy Staging App to Heroku?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/smart-home-auth-server#14]
As noted in https://github.com/dwyl/smart-home-firmware/issues/15#issuecomment-670084031 I think it might be more effective to run the "Hub" Phoenix App on Heroku instead of trying to run it on CI. By auto-deploying the latest `master` version to Heroku it's always current and we can debug things independently.

I have created a brand new (_separate_) Heroku Account so that the App gets the full [550 "free dyno hours"](https://devcenter.heroku.com/articles/free-dyno-hours) and we never have to worry about it being unavailable/offline.  https://github.com/dwyl/email/issues/38 | https://github.com/dwyl/auth/issues/88 `#LessonLearned` 🙄 

![image](https://user-images.githubusercontent.com/194400/89566626-5e3b9800-d818-11ea-97fa-a21b3d5fb03a.png)

Let me know your thoughts on this, I don't mind doing the setup and will share the access to the app once it's working.

**Comment by nelsonic** [comment]
App Created and Connected to GitHub for deployment on CI success:
![image](https://user-images.githubusercontent.com/194400/89586863-58ee4580-d838-11ea-9ecc-842305942d32.png)

Will need to add a few files and environment variables to make it work on Heroku, 
But I think it will be worth while to have a demo/staging version of the App. 💭

**Comment by nelsonic** [comment]
I've added Postgres, the Elixir Build Packs and the `AUTH_API_KEY` environment variable to the Heroku App. 
I will work on the rest after standup.

**Comment by t0mhaines** [comment]
This looks good, this should work well for testing as our firmware clients can't change the state of the Hub server, so we should be okay for running parallel tests etc.

**Comment by nelsonic** [comment]
@th0mas cool. thanks for confirming. I will proceed with deploying the app then. 👍

**Comment by nelsonic** [comment]
Deployment is blocked by failing tests #15 ⛔ 
@th0mas please address and LMK when I can proceed. ✅ 
Thanks! 🌻

**Comment by nelsonic** [comment]
Continue: https://dashboard.heroku.com/apps/smart-home-auth-server

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/89687245-c319ef80-d8f7-11ea-91bb-1c46d71fd17d.png)
```
GenServer #PID<0.258.0> terminating
** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) role "tomh" does not exist
```

**Comment by nelsonic** [comment]
Had to update `config/dev.exs`

From:
https://github.com/dwyl/smart-home-auth-server/blob/67f9883c6e21c50e8bf334018cfca42b27295474/config/dev.exs#L4-L8

To:
```elixir
# Configure your database
config :smart_home_auth, SmartHomeAuth.Repo,
  username: "postgres",
  password: "postgres",
  database: "smart_home_auth_dev",
  hostname: "localhost",
```

As per the "Run" instructions: https://github.com/dwyl/smart-home-auth-server/tree/67f9883c6e21c50e8bf334018cfca42b27295474#run

**Comment by nelsonic** [comment]
Deployed:
![image](https://user-images.githubusercontent.com/194400/89688631-80a5e200-d8fa-11ea-96c6-2d13c456fcd5.png)

https://smart-home-auth-server.herokuapp.com
![image](https://user-images.githubusercontent.com/194400/89688649-8d2a3a80-d8fa-11ea-8e3a-095df10ee062.png)

However after authenticating with my Google Account I see the following 500 Error Page:
![image](https://user-images.githubusercontent.com/194400/89688790-d67a8a00-d8fa-11ea-9abe-91fe3e4b42ef.png)

Heroku Logs for the request:
![image](https://user-images.githubusercontent.com/194400/89688846-f3af5880-d8fa-11ea-8bbc-8c68575cc924.png)

```
2020-08-07T21:19:42.942810+00:00 app[web.1]: ** (exit) an exception was raised:
2020-08-07T21:19:42.942852+00:00 app[web.1]:     ** (Protocol.UndefinedError) protocol Phoenix.HTML.Safe not implemented for %{errors: %{detail: "Internal Server Error"}} of type Map. 
This protocol is implemented for the following type(s): Decimal, Phoenix.LiveView.Comprehension, Phoenix.LiveComponent.CID, Phoenix.LiveView.Component, Phoenix.LiveView.Rendered, 
Phoenix.HTML.Form, Integer, BitString, NaiveDateTime, Atom, Time, List, Tuple, Date, DateTime, Float
2020-08-07T21:19:42.942853+00:00 app[web.1]:         (phoenix_html 2.14.2) lib/phoenix_html/safe.ex:1: Phoenix.HTML.Safe.impl_for!/1
2020-08-07T21:19:42.942854+00:00 app[web.1]:         (phoenix_html 2.14.2) lib/phoenix_html/safe.ex:15: Phoenix.HTML.Safe.to_iodata/1
2020-08-07T21:19:42.942854+00:00 app[web.1]:         (phoenix 1.5.3) lib/phoenix/controller.ex:776: Phoenix.Controller.render_and_send/4
2020-08-07T21:19:42.942854+00:00 app[web.1]:         (phoenix 1.5.3) lib/phoenix/endpoint/render_errors.ex:78: Phoenix.Endpoint.RenderErrors.instrument_render_and_send/5
2020-08-07T21:19:42.942855+00:00 app[web.1]:         (phoenix 1.5.3) lib/phoenix/endpoint/render_errors.ex:64: Phoenix.Endpoint.RenderErrors.__catch__/5
2020-08-07T21:19:42.942855+00:00 app[web.1]:         (phoenix 1.5.3) lib/phoenix/endpoint/cowboy2_handler.ex:65: Phoenix.Endpoint.Cowboy2Handler.init/4
2020-08-07T21:19:42.942856+00:00 app[web.1]:         (cowboy 2.8.0) /tmp/build_58a8ba63/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
2020-08-07T21:19:42.942856+00:00 app[web.1]:         (cowboy 2.8.0) /tmp/build_58a8ba63/deps/cowboy/src/cowboy_stream_h.erl:300: :cowboy_stream_h.execute/3
```

**Comment by nelsonic** [comment]
@th0mas when you're back from time off. It would be good to pair on this. 💭

**Comment by nelsonic** [comment]
Re-reading: https://hexdocs.pm/phoenix/heroku.html#making-our-project-ready-for-heroku 🔍

**Comment by nelsonic** [comment]
Ran the migration on Heroku:
```
heroku run "POOL_SIZE=2 mix ecto.migrate"
```

Restarted the App. 

Boom. Works.

https://smart-home-auth-server.herokuapp.com
![image](https://user-images.githubusercontent.com/194400/89692413-80f6ab00-d903-11ea-8a82-3dbb6622a216.png)

**Comment by nelsonic** [comment]
PR #19 assigned to @th0mas for when we're all back at our desks in a 10 days time. 👍

**Comment by nelsonic** [comment]
@th0mas please share the email address you use for Heroku on Signal so I can make you a collaborator 
so you can `heroku logs --tail` if you need to debug. 👍

**Comment by t0mhaines** [comment]
App deployed to Heroku and made accessible to collaborators, closing 👍

**Comment by t0mhaines** [comment]
![image](https://user-images.githubusercontent.com/9089056/90651572-1283e800-e235-11ea-9830-1bc3c9534743.png)

Can't seem to log into the auth server hosted on heroku?

**Comment by nelsonic** [comment]
Works via Google Auth:
![image](https://user-images.githubusercontent.com/194400/90656272-372e8e80-e23a-11ea-86d6-41b0e37b72ac.png)
![image](https://user-images.githubusercontent.com/194400/90656442-4281ba00-e23a-11ea-8709-051ca89eb991.png)

No logout implemented ... let me remove session manually.

Confirmed login with GitHub failing:
![image](https://user-images.githubusercontent.com/194400/90657655-9db3ac80-e23a-11ea-8cc4-707757584f32.png)

Uses https://github.com/dwyl/elixir-auth-github under the hood.
Checking: https://github.com/dwyl/elixir-auth-github-demo
![image](https://user-images.githubusercontent.com/194400/90657900-d81d4980-e23a-11ea-8555-b56ca19161b4.png)

GitHub Auth Works:
![image](https://user-images.githubusercontent.com/194400/90657928-dfdcee00-e23a-11ea-9d0e-c6dfe22a14f9.png)


Ok, now checking if the `auth_plug` works via: https://github.com/dwyl/auth_plug_example
![image](https://user-images.githubusercontent.com/194400/90658173-2599b680-e23b-11ea-8902-27ab30222022.png)
![image](https://user-images.githubusercontent.com/194400/90658201-2d595b00-e23b-11ea-817b-4715ebab44ce.png)

So I think the issue is that GitHub Auth is not passing through the email address.
This issue was noted in: https://github.com/dwyl/elixir-auth-github/issues/46
We need refactor Auth a bit so that the **`person`** record allows for **`username`** as the backup to **`email`** such that GitHub login can succeed even if the person has their email address hidden. 💭

**Comment by t0mhaines** [comment]
@nelsonic is it safe to say that the issue above is an `Auth` issue and a thread should be created there? That would allow us to close this issue thread

**Comment by nelsonic** [comment]
@th0mas yeah, it's definitely an **`auth`** issue. 👍

**Comment by SimonLab** [comment]
> We need refactor Auth a bit so that the person record allows for username as the backup to email such that GitHub login can succeed even if the person has their email address hidden

The possible future issue by using the Github username when the email is not available is that the username can be changed in Github: https://docs.github.com/en/enterprise/2.14/user/articles/changing-your-github-username

![image](https://user-images.githubusercontent.com/6057298/90902010-b8fdf380-e3c3-11ea-9f2c-0f4f294581a3.png)

At the moment the email is used to retreive or create the person:
https://github.com/dwyl/auth/blob/fafc5e059d65de420b4d99bf1d15ac45a3bcda12/lib/auth/person.ex#L222-L237

So using the username when the email is not defined could possibly allow another person to access information of a user who has recently updated her username.

I suggest that instead of allowing people to login/register with Github when the email is hidden we display an error message explaining that an email is required.

**Comment by nelsonic** [comment]
@SimonLab Yeah, requiring email when their GitHub account does not return one could be a better option. 
(_more work but better_)
