### ISSUE TITLE
24 Tests Fail on Master Branch

### ISSUE THREAD

**Issue by nelsonic** [dwyl/smart-home-auth-server#15]
Hi @th0mas, hope your morning is going well. 
I tried to run the tests on the **`master`** branch of this project on my **`localhost`** and  I get  the following error:

![image](https://user-images.githubusercontent.com/194400/89634396-34788480-d89d-11ea-9197-8d77e6f28428.png)

Appears to be related to the feature flags. 💭 

This is matches what we see on Travis-CI where the last few builds have failed:
https://travis-ci.com/github/dwyl/smart-home-auth-server/branches
![image](https://user-images.githubusercontent.com/194400/89634440-507c2600-d89d-11ea-8b13-e177a566704d.png)

The most recent **`master`** build is:
https://travis-ci.com/github/dwyl/smart-home-auth-server/builds/178230954#L892
![image](https://user-images.githubusercontent.com/194400/89634228-f4190680-d89c-11ea-926e-666ee69c85c5.png)

Please take a look at the failing tests and ensure that they all pass on **`master`**  (_create a branch/PR to fix the tests_) 
and let me know when it's done so I can proceed with the Heroku deployment #14 
Thanks. ✨

**Comment by t0mhaines** [comment]
@nelsonic Yeah I was delaying rewriting the tests until the authorization system properly working with RBAC as ~60% of the tests and systems will be affected by this. I'm happy to try and fix the tests that are broken now but I won't aim for a high coverage until RBAC is complete and I know how much of the hub needs to be adapted

**Comment by t0mhaines** [comment]
Theres a few bugs in the smart hub (#7, #11) that need to be fixed before a "production" release of this but will be rewritten/significantly changed to work with RBAC in the future.

**Comment by nelsonic** [comment]
Ah ... OK. If this is dependent on RBAC, please see/answer https://github.com/dwyl/smart-home-auth-server/issues/1#issuecomment-670448196 ❓ 
I will switch back to RBAC now and focus on that. 👍

**Comment by t0mhaines** [comment]
Its not RBAC *dependent* per se, and there's still a few broken tests from #7 that I'll fix now and I'll comment out all the authorization tests for now so we can get deployment working. 

But most of the tests will rely on a RBAC implementation so we'll probably only end up with 30-40% coverage *for now*.

**Comment by nelsonic** [comment]
@th0mas OK. if that's the case, fix the tests you _can_ fix (_as you've said_) and if we can get `master` in a stable/deployable state even with low coverage I will get that done today so that you can use the Heroku instance in the firmware tests. 👍
