### ISSUE TITLE
Generate JWT tokens locally for development

### ISSUE THREAD

**Issue by t0mhaines** [dwyl/smart-home-auth-server#21]
Whatever we end up doing for https://github.com/dwyl/smart-home-security-system/issues/11, we need to be able to programatically generate JWT tokens locally for API development.

This will also be useful for testing in future

**Comment by nelsonic** [comment]
https://github.com/dwyl/auth_plug/blob/cbcc34b6f566264a3663850ca29f35329f3bab8e/lib/token.ex#L58-L60 💭
