### ISSUE TITLE
Setup coverage on CI

### ISSUE THREAD

**Issue by t0mhaines** [dwyl/smart-home-auth-server#6]
I've tried to setup coverage on Travis CI but so far have not managed to get it to work.

@nelsonic I don't want to spend my day fighting with config files so are you able to take a look at this?

**Comment by nelsonic** [comment]
@th0mas i will take a look at it. 👍🏻

**Comment by nelsonic** [comment]
Codecov working: [![Build Status](https://img.shields.io/travis/com/dwyl/smart-home-auth-server/master.svg?style=flat-square)](https://travis-ci.com/github/dwyl/smart-home-auth-server) [![codecov.io](https://img.shields.io/codecov/c/github/dwyl/smart-home-auth-server/master.svg?style=flat-square)](http://codecov.io/github/dwyl/smart-home-auth-server?branch=master)

https://travis-ci.com/github/dwyl/smart-home-auth-server/builds/174648177#L450

![image](https://user-images.githubusercontent.com/194400/86806430-c3ad3500-c070-11ea-9124-820e3a9eb3e2.png)

https://codecov.io/github/dwyl/smart-home-auth-server
